# CI Workers Builds project name (repo: tarkovcheats)
name = "tarkovcheats"
compatibility_date = "2026-01-01"
pages_build_output_dir = "dist"

[assets]
directory = "./dist"
not_found_handling = "404-page"
